# Enable the build-std feature so that we can re-build `core` for our custom target triple (x86_64_os.json)
[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

# Set the default build target to our custom target triple so we don't need to specify on CLI
[build]
target = "x86_64_os.json"
